close all;
% Create a customized GUI.
config; %camera presets

f1 = figure('Name', 'Preview Window'); 
uicontrol('String', 'Close', 'Callback', 'close(gcf)');  
% set(f1, 'Position', [30, 30, 600, 600]);



vidRes = vid.VideoResolution; 
nBands = vid.NumberOfBands; 
hImage = image( zeros(vidRes(2), vidRes(1), nBands) ); 
% Create an image object for previewing
prev=preview(vid, hImage);  



                
                
h=-5;l=20;
% Create controll objects
sld_Gain = uicontrol('Style', 'slider',...
        'Min',Gain_constrains(1),'Max',Gain_constrains(2),'Value',sum(Gain_constrains)/2,...
        'Position', [400 20 120 10],'Tag','gain',...
        'Callback', @(hObject,event) sld_gain(src,src_prop_set,vid)); 
txt_Gain = uicontrol('Style','text','String','Gain','Position', [520 20+h 40+l 20],...
        'FontSize',10,'Fontname','Helvetica','Fontweight','bold','HorizontalAlignment','left');

sld_Gamma = uicontrol('Style', 'slider',...
        'Min',Gamma_constrains(1),'Max',Gamma_constrains(2),'Value',sum(Gamma_constrains)/2,...
        'Position', [400 40 120 10],'Tag','gamma',...
        'Callback', @(hObject,event) sld_gamma(src,src_prop_set,vid));  
txt_Gamma = uicontrol('Style','text','String','Gamma','Position', [520 40+h 40+l 20],...
        'FontSize',10,'Fontname','Helvetica','Fontweight','bold','HorizontalAlignment','left');

sld_Exposure = uicontrol('Style', 'slider',...
        'Min', Exposure_constrains(1),'Max',Exposure_constrains(2),'Value',sum(Exposure_constrains)/2,...
        'Position', [400 60 120 10],'Tag','exposure',...
        'Callback', @(hObject,event) sld_exposure(src,src_prop_set,vid));
txt_Exposure = uicontrol('Style','text','String','Expos.','Position', [520 60+h 40+l 20],...
        'FontSize',10,'Fontname','Helvetica','Fontweight','bold','HorizontalAlignment','left');

sld_Brightness = uicontrol('Style', 'slider',...
        'Min',Brightness_constrains(1),'Max',Brightness_constrains(2),'Value',sum(Brightness_constrains)/2,...
        'Position', [400 80 120 10],'Tag','brightness',...
        'Callback', @(hObject,event) sld_brightness(src,src_prop_set,vid));  
txt_Brightness = uicontrol('Style','text','String','Bright.','Position', [520 80+h 40+l 20],...
        'FontSize',10,'Fontname','Helvetica','Fontweight','bold','HorizontalAlignment','left');

sld_Saturation = uicontrol('Style', 'slider',...
        'Min',Saturation_constrains(1),'Max',Saturation_constrains(2),'Value',sum(Saturation_constrains)/2,...
        'Position', [400 100 120 10],'Tag','saturation',...
        'Callback', @(hObject,event) sld_saturation(src,src_prop_set,vid));  
txt_Saturation = uicontrol('Style','text','String','Sat.','Position', [520 100+h 40+l 20],...
        'FontSize',10,'Fontname','Helvetica','Fontweight','bold','HorizontalAlignment','left');

sld_Contrast = uicontrol('Style', 'slider',...
        'Min',Contrast_constrains(1),'Max',Contrast_constrains(2),'Value',sum(Contrast_constrains)/2,...
        'Position', [400 120 120 10],'Tag','contrast',...
        'Callback', @(hObject,event) sld_contrast(src,src_prop_set,vid));  
txt_Contrast = uicontrol('Style','text','String','Contr.','Position', [520 120+h 40+l 20],...
        'FontSize',10,'Fontname','Helvetica','Fontweight','bold','HorizontalAlignment','left');

sld_WhiteBalance = uicontrol('Style', 'slider',...
        'Min',WhiteBalance_constrains(1),'Max',WhiteBalance_constrains(2),'Value',sum(WhiteBalance_constrains)/2,...
        'Position', [400 140 120 10],'Tag','whitebalance',...
        'Callback', @(hObject,event) sld_whitebalance(src,src_prop_set,vid));  
txt_WhiteBalance = uicontrol('Style','text','String','WB','Position', [520 140+h 40+l 20],...
        'FontSize',10,'Fontname','Helvetica','Fontweight','bold','HorizontalAlignment','left');



